# Make sure you copy oberviewer_config.py to the input directory

overviewer:
  build: .
  container_name: minecraft-overviewer
  volumes:
    - "/media/dockerdata/minecraft/mcdata/world:/var/in"
    - "/media/dockerdata/overviewer/Minecraft-Overviewer/out/Novi:/var/out"   
